### ISSUE TITLE
Fine-tuning specific areas

### ISSUE THREAD

**Issue by peng06051126** [paperswithcode/galai#65]
First of all, thank you for your great contribution. I would like to fine-tune galactica in the direction of generating articles from topics. Can you provide training data samples, or do you have any suggestions?

**Comment by mkardas** [comment]
The Galactica models were pretrained on large amount of papers (see our paper for more details):

<img width="575" alt="image" src="https://user-images.githubusercontent.com/13535078/210371189-a5f74521-81f8-41c1-9538-94408473b4cb.png">

so you should be able to generate articles out-of-the-box, but it depends on your use case.

**Comment by peng06051126** [comment]
Thank you for your reply. May I ask how the model performs on non-English data? Has there been any relevant test? And what proportion does non-English data take in the pre-training data set, such as Chinese data, etc.

**Comment by mkardas** [comment]
By design the models are not multi-lingual and most of the natural language documents in the pretraining corpus are written in English. See more in [Introduction to GALACTICA Models](https://github.com/paperswithcode/galai/blob/main/notebooks/Introduction%20to%20Galactica%20Models.ipynb) notebook (look for "multi-lingual").
